### ISSUE TITLE
conda environment creation error

### ISSUE THREAD

**Issue by albutko** [lenck/vlb#17]
When running `conda env create -f ./python/conda/environment.yml` the below error is thrown and build fails.

ResolvePackageNotFound
![image](https://user-images.githubusercontent.com/15615810/53771296-10e32a80-3eb0-11e9-9f2b-4ea60db05a24.png)

**Comment by spongezhang** [comment]
Fix the dead link #18  and update the installation guide  #19.

**Comment by albutko** [comment]
I am still having issues with `libgcc-ng` and `libstdcxx-ng`. I believe there are caused by operating system discrepancy; I am running MacOS. I have created `environment_mac.yml` that installs the analogous MacOS packages.

**Comment by spongezhang** [comment]
Did it work right now? It should be safe to remove these two packages from yml file. Conda should be able to figure it out by itself.

**Comment by spongezhang** [comment]
#20 fixed. Issue closed.
