### ISSUE TITLE
patch reader and writer

### ISSUE THREAD

**Issue by spongezhang** [lenck/vlb#2]
Hi Karel, 

I can't understand why you support that the color channel of the patch can be either the 3rd channel or the 4th channel. 

`function patches_save(patches, respath, scalingFactor)
assert(size(patches, 3) == 1 || size(patches, 3) == 3, ...
  'Patches has to be stored along 4th dimension.');`

That's very confusing. If there are only 3 patches, that will be a problem. 

Best,
Xu

**Comment by lenck** [comment]
Hi,
if I understand correctly your question, this is a sort of "help" assert to make sure that the patches are along the 4th dimension, no matter whether they are grayscale or RGB. So the size of the patches should be always `H x W x 1 x N` or `H x W x 3 x N`.

I did this this way as I think allowing patches to be along 3rd or 4th dimension can cause more issues (as you say, then a 1 RGB patch might look like 3 grayscale patches).

**Comment by lenck** [comment]
Ah... You meant this error:
```
Error using vl_imarray (line 62)
A is neither M*N*K, nor M*N*3*K, nor M*N*K*3.

Error in vlb_view>view_patches (line 77)
  imshow(vl_imarray(res));

Error in vlb_view (line 25)
    cmds.(cmd).fun(varargin{:});

Error in vlb (line 38)
    cmds.(cmd).fun(varargin{:});

Error in detbench (line 23)
vlb('view', 'patches', imdb, feat, 1);
```
Just got it now. It's because I was developing it with my branch of vlfeat which has a more clever vl_imarray. Now it should be fixed...

**Comment by spongezhang** [comment]
Send you a new pull request to deal with this issue. I also meant the
vl_imarray file, see the code.

  if ndims(A) == 4 && (size(A,3) == 3 || size(A,3) == 1)
    [height,width,numChannels,numImages] = size(A) ;
  elseif ndims(A) == 4 && size(A,4) == 3 ;
    swap3 = true ;
    [height,width,numImages,numChannels] = size(A) ;
  else
    error('A is neither M*N*K, nor M*N*1*K, nor M*N*3*K, nor M*N*K*3.') ;
  end

To swap the channel by watching the channel number of the last dimension
seems to be very weird. Assume there has only three patches. Let's keep the
last dimension to be the patch index from now on. :)

Best,
Xu

**Comment by spongezhang** [comment]
Agree to keep the same array format. "M N C K" seems OK for me. Let us just keep it for this point. :)
